### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by bergpb** [Nephiel/NFCLockScreenOffEnablerMM#4]
Hi, nice work, but not work for me.
Sony Z3 compact, on marshmallow.
Any function work.

**Comment by Nephiel** [comment]
Hi, not sure where the problem is. But for the Z3 compact you can find more info here: http://forum.xda-developers.com/z3-compact/themes-apps/nfc-screenoff-mod-t3109519
As always, remember to make backups, and do it at your own risk.
